---

- name: Install dependencies
  become: true
  ansible.builtin.apt:
    pkg:
      - nfs-common

- name: Create NFS mount
  become: true
  ansible.posix.mount:
    src: "{{ nfs_server }}:{{ server_mount }}"
    path: "{{ client_mount }}"
    state: mounted
    fstype: nfs
    opts: defaults,rw,nofail
    boot: false

