---

- hosts: controller
  roles:
    - roles/slurmctld
    - roles/compute
    - roles/nfs-server
  vars:
    all_nodes: "{{ groups['workers'] + groups['controller'] }}"
    workers: "{{ groups['workers'] }}"
    cluster_name: "anshul_test_cluster"
    nfs_user: "ubuntu"
    server_mount: "/mnt/{{nfs_user}}"
