- hosts: workers
  roles:
    - roles/compute
  vars:
    all_nodes: "{{ groups['workers'] + groups['controller'] }}"
    gres_conf_template: "l40s_48gb_1x.j2"
    hosts_to_gpu_counts: "{{ hostvars['workers'] | dict2items | map('extract', 'gpu_count')  }}"
